version: '3.9'

services:
  mariadb_exported:
    image: mariadb:10.5
    container_name: moodle_db_exported
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - moodle_net

  moodle_exported:
    image: moodlehq/moodle-php-apache:7.4
    container_name: moodle_exported
    restart: unless-stopped
    depends_on:
      - mariadb_exported
    ports:
      - "80:80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata1:/var/www/moodledata1
    environment:
      MOODLE_DOCKER_DBTYPE: mariadb
      MOODLE_DOCKER_DBHOST: mariadb_exported
    networks:
      - moodle_net

networks:
  moodle_net:
    driver: bridge
