# docker-compose.yml
version: '3.8'
services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:   moodle
      MYSQL_USER:       moodle
      MYSQL_PASSWORD:   moodle
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./moodle:/var/www/html:ro
      - ./moodledata:/var/www/moodledata
    restart: always

volumes:
  db_data:
